products_products:
    resource: "@VitchkovskiProductsBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /logout

login:
    path: /login
    defaults: { _controller: VitchkovskiProductsBundle:Security:login}
