products_products:
    resource: "@ProductsProductsBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /logout

login:
    path: /login
    defaults: { _controller: ProductsProductsBundle:Security:login}
