<?php

namespace Products\ProductsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoriesForProduct($productId)
    {
        $qb = $this->createQueryBuilder('uc')
            ->select('c')
            ->from('ProductsProductsBundle:Category', 'c')
            ->innerJoin('c.products_x_categories','pxc')
            ->where('pxc.product = :productId')
            ->setParameter('productId', $productId);

        return $qb->getQuery()
            ->getResult();
    }
}
