<?php

namespace Vitchkovski\ProductsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoryByUser($category_id, $user_id)
    {
        $qb = $this->getEntityManager()->createQuery('SELECT c FROM VitchkovskiProductsBundle:Category c 
        LEFT JOIN c.product p  
        WHERE c.category_id = :category_id
          and p.user = :user_id')
            ->setParameter('user_id', $user_id)
            ->setParameter('category_id', $category_id);

        return $qb->getOneOrNullResult();

    }
}
