<?php

namespace Vitchkovski\ProductsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoriesForProduct($productId)
    {
        $qb = $this->createQueryBuilder('uc')
            ->select('c')
            ->from('VitchkovskiProductsBundle:Category', 'c')
            ->leftJoin('c.product', 'p')
            ->where('p.product_id = :productId')
            ->setParameter('productId', $productId);

        return $qb->getQuery()
            ->getResult();
    }
}
