<?php

namespace Vitchkovski\ProductsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductWithCategories($productId, $userId)
    {
        $qb = $this->createQueryBuilder('productRepository')
            ->select('p', 'c')
            ->from('VitchkovskiProductsBundle:Product', 'p')
            ->leftJoin('p.categories', 'c')
            ->where('c.product = :productId')
            ->andWhere('productRepository.user = :user_id')
            ->setParameter('user_id', $userId)
            ->setParameter('productId', $productId);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }
}
