services:
    app.image_uploader:
        class: Vitchkovski\ProductsBundle\Services\ImageUploader
        arguments: ['../web/uploads/']
    app.token_authenticator:
        class: Vitchkovski\ProductsBundle\Services\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]
    app.users_service:
        class: Vitchkovski\ProductsBundle\Services\UsersService
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    app.products_service:
        class: Vitchkovski\ProductsBundle\Services\ProductsService
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
